### ISSUE TITLE
feat: add `up -e/--env` support

### ISSUE THREAD

**Issue by starpit** [IBM/lunchpail#393]
**Is your feature request related to a problem? Please describe.**
`-e foo=bar` would be sugaring over `--set foo=bar` and an app.yaml that sets the corresponding env var based on helm templates, e.g.

```yaml
env:
  - name: foo
     value: {{ .Values.foo }}
```

The advantage being the application owner doesn't need to be the conduit for env vars into the app. Instead, lunchpail can do this for them.
